// Auto-generated by tools/version.mjs
export const APP_VERSION = "0.0.14+20251029.0018";
export const BUILD_TIME_UTC = "2025-10-29T00:18:02.805Z";
export const GIT_SHA = "4570bbd6562c69868569d6293d9ead03d6f09a2f";
export const PRODUCT_VERSION = "0.7.1";
