// Auto-generated by tools/version.mjs
export const APP_VERSION = "0.0.15+20251029.0055";
export const BUILD_TIME_UTC = "2025-10-29T00:55:05.809Z";
export const GIT_SHA = "f1581090cbc44cb742afa5b21215577c1e79ba53";
export const PRODUCT_VERSION = "0.7.1";
