// Auto-generated by tools/version.mjs
export const APP_VERSION = "0.0.5+20251028.1817";
export const BUILD_TIME_UTC = "20251028.1817";
export const GIT_SHA = "35405338f9be67dd1ac8f64010eab85f37998047";
