name: Build Atlas
on:
  push:
    branches: [ main ]
    paths:
      - "**/*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  atlas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm i globby gray-matter js-yaml ignore
      - run: node tools/atlas.mjs
        env:
          ATLAS_OUT: docs/ATLAS.md
      - name: Commit Atlas
        run: |
          git config user.name "jiraless-bot"
          git config user.email "bot@users.noreply.github.com"
          git add docs/ATLAS.md
          git diff --cached --quiet || git commit -m "atlas: refresh snapshot"
          git push