name: Federate Cortex
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - "docs/ATLAS.md"

permissions:
  contents: write
  pull-requests: write

jobs:
  federate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm i js-yaml node-fetch
      - run: node tools/federate.mjs
      - name: Create/Update Rolling PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "cortex: update federated view"
          title: "federated-snapshots"
          body: "Automated update of federated cortex snapshots"
          branch: federated-snapshots
          labels: |
            automation
            snapshots
          delete-branch: true