name: Deploy UI to Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install root deps
        run: npm ci

      - name: Install UI deps
        working-directory: ui
        run: npm ci

      - name: Materialize views (boards, backlinks, state-machine)
        run: node tools/materialize.mjs

      - name: Assert state-machine present
        run: |
          test -f ui/public/state-machine.json || (echo "ui/public/state-machine.json missing" && exit 1)
          test -f .project/views/state-machine.json || (echo ".project/views/state-machine.json missing" && exit 1)

      - name: Version bump and health files
        run: node tools/version.mjs

      - name: Build UI (root base)
        working-directory: ui
        env:
          VITE_BASE: /
        run: |
          echo "Building UI..."
          npm run build
          echo "Built files:"
          ls -lah dist
          du -sh dist
          echo "APP_VERSION: $(cat src/version.ts | grep APP_VERSION | cut -d'"' -f2)"
          echo "PRODUCT_VERSION: $(cat src/version.ts | grep PRODUCT_VERSION | cut -d'"' -f2)"

      - name: Add CNAME
        run: echo "jiraless.levratech.com" > ui/dist/CNAME

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ui/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4