name: Deploy UI to Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:
    types: [ jiraless.deploy ]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # DIAGNOSTICS: print event + changed files
      - name: Event + Diff
        run: |
          echo "EVENT: ${{ github.event_name }}"
          echo "REF:    ${{ github.ref }}"
          echo "SHA:    ${{ github.sha }}"
          git --no-pager log --oneline -n 5
          echo "--- changed files vs parent ---"
          (git diff --name-only HEAD^ || true) | sed 's/^/CHANGED: /'

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Materialize views
        run: node tools/materialize.mjs

      - name: Version stamp
        run: node tools/version.mjs

      - name: Build UI
        working-directory: ui
        run: |
          npm ci
          npm run build

      - name: Assert no stale base
        working-directory: ui/dist
        run: |
          if grep -R "/jiraless/" -n .; then
            echo "❌ Found hardcoded /jiraless/ in built files"
            exit 1
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ui/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
    steps:
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Verify live version (best-effort)
        continue-on-error: true
        run: |
          sleep 8
          curl -fsSL https://jiraless.levratech.com/version.json || (echo "version.json not reachable yet" && exit 0)