name: Pages Watchdog
on:
  schedule: [ { cron: "0 * * * *" } ]  # hourly
  workflow_dispatch:
permissions: {}
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fail if no pages deploy in last 2 hours
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          LATEST_TS=$(gh api repos/${{ github.repository }}/deployments \
            --paginate -q '.[].created_at' | head -n1)
          echo "LATEST_DEPLOY: $LATEST_TS"
          if [ -z "$LATEST_TS" ]; then
            echo "No deployments found"; exit 1
          fi
          NOW=$(date -u +%s)
          DEP=$(date -u -d "$LATEST_TS" +%s)
          DIFF=$(( (NOW-DEP)/3600 ))
          echo "Hours since deploy: $DIFF"
          if [ "$DIFF" -ge 2 ]; then
            echo "Pages hasn’t deployed in >=2 hours"; exit 1
          fi