name: Deploy UI to Pages

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/ATLAS.md'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install
        run: npm ci

      # If UI is in a subfolder with its own package.json, install & build there
      - name: Detect UI dir
        id: detect
        run: |
          if [ -f ui/package.json ]; then
            echo "ui_dir=ui" >> $GITHUB_OUTPUT
          else
            echo "ui_dir=." >> $GITHUB_OUTPUT
          fi

      - name: Install UI deps (if any)
        if: steps.detect.outputs.ui_dir == 'ui'
        run: |
          set -euxo pipefail
          cd ui
          npm ci || true

      - name: Build UI (root base)
        env:
          VITE_BASE: /
        run: |
          set -euxo pipefail
          cd ${{ steps.detect.outputs.ui_dir }}
          npm run build
          echo "Built files:"
          ls -lah dist || true

      - name: Assert dist exists
        run: |
          test -d ${{ steps.detect.outputs.ui_dir }}/dist || (echo "::error::dist not found" && exit 1)

      - name: Add CNAME
        run: |
          echo "jiraless.levratech.com" > ${{ steps.detect.outputs.ui_dir }}/dist/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.detect.outputs.ui_dir }}/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4