name: Pages Watchdog
on:
  schedule: [ { cron: "*/15 * * * *" } ]
  workflow_dispatch:
permissions:
  contents: read
  issues: write
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Get latest commit SHA
        id: latest_sha
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
      - name: Check site version
        id: check_version
        run: |
          RESPONSE=$(curl -s -w "HTTPSTATUS:%{http_code}" "https://jiraless.levratech.com/version.json?x=${{ github.run_id }}")
          HTTP_STATUS=$(echo "$RESPONSE" | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
          BODY=$(echo "$RESPONSE" | sed -e 's/HTTPSTATUS:.*//g')
          
          echo "HTTP Status: $HTTP_STATUS"
          
          if [ "$HTTP_STATUS" != "200" ]; then
            echo "Site is down or unreachable (HTTP $HTTP_STATUS)"
            echo "stale=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          SITE_SHA=$(echo "$BODY" | jq -r '.git_sha // empty')
          LATEST_SHA="${{ steps.latest_sha.outputs.sha }}"
          
          echo "Site SHA: $SITE_SHA"
          echo "Latest SHA: $LATEST_SHA"
          
          if [ "$SITE_SHA" != "$LATEST_SHA" ]; then
            echo "Site SHA does not match latest commit"
            echo "stale=true" >> $GITHUB_OUTPUT
          else
            echo "Site is up to date"
            echo "stale=false" >> $GITHUB_OUTPUT
          fi
      - name: Create/update stale issue
        if: steps.check_version.outputs.stale == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const title = "Pages stale";
            const body = `
            ## Pages Deployment Issue
            
            The site at https://jiraless.levratech.com appears to be stale or unreachable.
            
            - Latest commit: ${{ steps.latest_sha.outputs.sha }}
            - Site SHA: ${{ steps.check_version.outputs.site_sha || 'unreachable' }}
            - Checked at: ${new Date().toISOString()}
            
            Please check the Pages deployment status.
            `;
            
            // Find existing issue
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['pages-stale'],
              state: 'open'
            });
            
            if (issues.data.length > 0) {
              // Update existing issue
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issues.data[0].number,
                body: body
              });
            } else {
              // Create new issue
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: title,
                body: body,
                labels: ['pages-stale', 'bug']
              });
            }
      - name: Fail if stale
        if: steps.check_version.outputs.stale == 'true'
        run: |
          echo "Site is stale - failing job to alert"
          exit 1