name: Deploy UI to Pages
on:
  push:
    branches: [ main ]
    paths:
      - "ui/**"
      - ".project/**"
      - "tools/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 1) Materialize canonical views and mirror to ui/public
      - name: Materialize views
        run: |
          npm i -D globby gray-matter js-yaml
          TARGET_PUBLIC=ui/public node tools/materialize.mjs

      # 2) Build the UI (includes ui/public/views/* + ontology.json)
      - name: Build UI
        working-directory: ui
        run: |
          npm ci
          npm run build

      # 3) Upload and deploy
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ui/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v4